version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:

      test: ["CMD", "pg_isready", "-U", "user", "-d", "recipe_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: recipe_db
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
